name: HydraDX Subsquid Deployment

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_ACC: ${{ secrets.DOCKERHUB_ACC }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_ACC }}
        password: ${{ env.DOCKERHUB_PASS }}
    
    - name: Build Processor image
      run: docker build . --target processor -t ${DOCKERHUB_ACC}/hydradx-reserves
    
    - name: Build Query-node image
      run: docker build . --target query-node -t ${DOCKERHUB_ACC}/hydradx-reserves-qn
    
    - name: Push Processor image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${DOCKERHUB_ACC}/hydradx-reserves

    - name: Push Query-node image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${DOCKERHUB_ACC}/hydradx-reserves-qn