name: HydraDX Subsquid Deployment

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_ACC: ${{ secrets.DOCKERHUB_ACC }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  ORG: galacticcouncil
  CGP_PROJECT_ID: rich-principle-383410
  CGP_SERVICE_NAME: squid-sa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_ACC }}
        password: ${{ env.DOCKERHUB_PASS }}

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.CGP_PROJECT_ID }}
        service_account_key: ${{ secrets.CGP_PROJECT_PASS }}
        export_default_credentials: true
    
    - name: Build Processor image
      run: docker build . --target processor -t gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:processor-latest
    
    - name: Build Query-node image
      run: docker build . --target query-node -t gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:query-node-latest
    
    - name: Debug - List images
      run: docker images

    - name: Push Processor image
      run: |
        docker push gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:processor-latest
        gcloud run deploy ${CGP_SERVICE_NAME}-processor \
          --image gcr.io/${CGP_PROJECT_ID}/${CGP_SERVICE_NAME}:processor-latest \
          --platform managed \
          --allow-unauthenticated

    - name: Push Query-node image
      run: |
        docker push gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:query-node-latest
        gcloud run deploy ${CGP_SERVICE_NAME}-query-node \
          --image gcr.io/${CGP_PROJECT_ID}/${CGP_SERVICE_NAME}:query-node-latest \
          --platform managed \
          --allow-unauthenticated
