name: HydraDX Subsquid Deployment

on:
  push:
    branches: [ main ]

env:
  PROJECT: rich-principle-383410
  LOCATION: europe-west3
  REPOSITORY: hydradx-squid
  SERVICE: hydradx-squid

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.CGP_PROJECT_PASS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Set up Docker
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev
    
    # - name: Build Processor image
    #   run: docker buildx build . --target processor -t ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest --platform linux/amd64
    
    - name: Debug - List images
      run: docker images
    
    # - name: IAM policy helper
    #   run: gcloud run services add-iam-policy-binding --region=${{ env.LOCATION }} --member=allUsers --role=roles/run.invoker ${{ env.SERVICE }}-processor

    # - name: Push & Deploy Processor image
    #   run: |
    #     docker push ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest
    #     gcloud run deploy ${SERVICE}-processor \
    #       --image ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest \
    #       --platform managed \
    #       --region europe-west3 \
    #       --allow-unauthenticated \
    #       --memory 4000Mi

    - name: Pull & Push & Deploy archive ingest
      run: |
        docker pull subsquid/substrate-ingest:firesquid
        docker tag subsquid/substrate-ingest:firesquid ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest
        docker push ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest
        gcloud run deploy ${SERVICE}-ingest \
          --image ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest \
          --region europe-west3 \
          --platform managed \
          --allow-unauthenticated \
          --command='-e wss://rpc.hydradx.cloud -c 20 --out postgres://squid:squid@squid:5432/squid'

    - name: Pull & Push & Deploy archive gateway
      run: |
        docker pull subsquid/substrate-gateway:firesquid
        docker tag subsquid/substrate-gateway:firesquid ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest
        docker push ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest
        gcloud run deploy ${SERVICE}-gateway \
          --image ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest \
          --region europe-west3 \
          --platform managed \
          --allow-unauthenticated \
          --command "--database-url postgres://squid:squid@squid:5432/squid --database-max-connections 5" \
          --port 8000