name: HydraDX Subsquid Deployment

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_ACC: ${{ secrets.DOCKERHUB_ACC }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  ORG: galacticcouncil
  CGP_PROJECT_ID: rich-principle-383410
  CGP_SERVICE_NAME: squid-sa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.CGP_PROJECT_PASS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: Build Processor image
      run: docker buildx build . --target processor -t gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:processor-latest --platform linux/amd64
    
    - name: Build Query-node image
      run: docker buildx build . --target query-node -t gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:query-node-latest --platform linux/amd64
    
    - name: Debug - List images
      run: docker images

    - name: Docker credential helper
      run: gcloud auth configure-docker -q
    
    - name: Push Processor image
      run: docker push gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:processor-latest
        
    - name: Deploy processor image
      run: gcloud run deploy ${CGP_SERVICE_NAME}-processor \
          --image gcr.io/${CGP_PROJECT_ID}/${CGP_SERVICE_NAME}:processor-latest \
          --platform managed \
          --region europe-west3 \
          --allow-unauthenticated \
          --memory 4000Mi

    - name: Push Query-node image
      run: docker push gcr.io/${{ env.CGP_PROJECT_ID }}/${{ env.CGP_SERVICE_NAME }}:query-node-latest
        
    - name: Deploy Query-node image
      run: gcloud run deploy ${CGP_SERVICE_NAME}-query-node \
          --image gcr.io/${CGP_PROJECT_ID}/${CGP_SERVICE_NAME}:query-node-latest \
          --platform managed \
          --region europe-west3 \
          --allow-unauthenticated \
          --memory 4000Mi
