name: HydraDX Subsquid Deployment

on:
  push:
    branches: [ main ]

env:
  GCP_PROJECT_ID: rich-principle-383410
  GCP_SERVICE_NAME: squid-sa
  GCP_INSTANCE: rich-principle-383410:europe-west3:squid
  GAR_LOCATION: europe-west3
  REPOSITORY: hydradx-squid
  SERVICE: hydradx-squid

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.CGP_PROJECT_PASS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Set up Docker
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev
    
    - name: Build Processor image
      run: docker buildx build . --target processor -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest --platform linux/amd64
    
    - name: Debug - List images
      run: docker images
    
    - name: IAM policy helper
      run: gcloud run services add-iam-policy-binding --region=${{ env.GAR_LOCATION }} --member=allUsers --role=roles/run.invoker ${{ env.GCP_SERVICE_NAME }}-processor

    - name: Push & Deploy Processor image
      run: |
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest
        gcloud run deploy ${GCP_SERVICE_NAME}-processor \
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest \
          --platform managed \
          --region europe-west3 \
          --allow-unauthenticated \
          --memory 4000Mi

    - name: Push & Deploy archive ingest
      run: |
        docker tag docker.io/subsquid/substrate-ingest:firesquid ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest
        gcloud run deploy ${GCP_SERVICE_NAME}-ingest \
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-ingest:latest \
          --command='-e wss://rpc.hydradx.cloud -c 20 --out postgres://squid:squid@squid:5432/squid'

    - name: Push & Deploy archive gateway
      run: |
        docker tag docker.io/subsquid/substrate-gateway:firesquid ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest
        gcloud run deploy ${GCP_SERVICE_NAME}-gateway \
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}-gateway:latest \
          --command "--database-url postgres://squid:squid@squid:5432/squid --database-max-connections 5" \
          --port 8000